### ISSUE TITLE
Autocorrect language name typos (like Git does for commands)

### ISSUE THREAD

**Issue by stevenzeck** [Unibeautify/unibeautify-cli#115]
_From @muuvmuuv on October 29, 2018 7:10_

**Describe the feature**

I have started working more with the Unibeautify CLI and had noticed that it is really hard to understand how it is working. I started with `unibeautify index.js -l javascript`, then I saw that I need to flag the file with `-f` and after a talk with @stevenzeck (See: [unibeautify-cli/issues/103](https://github.com/Unibeautify/unibeautify-cli/issues/103#issuecomment-433601293)) I had to letter `javascript` correctly. So the correct way was `unibeautify -f index.js -l JavaScript`. 

This is IMHO,  a little bit to difficult for the most users because not every developer knows the correct lettering of every language. I think we need to make this case intensitive. The corresponding lines are [LanguageManager.ts#L18](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L18) and [LanguageManager.ts#L25](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L25)

_Copied from original issue: Unibeautify/unibeautify#208_

**Comment by stevenzeck** [comment]
_From @lassik on October 29, 2018 7:57_

I agree. We haven't done a lot of work on the CLI yet. Hopefully the pace is picking up soon :)

**Comment by stevenzeck** [comment]
_From @Glavin001 on October 29, 2018 13:43_

I think your reasoning makes sense.

I would prefer to keep the name to be correct and exact. However, I also want the user experience to be better. How about for the time being we make autocorrect / recommendations to the user like `git` does? See https://stacktoheap.com/blog/2015/11/01/git-autocorrect-feature/ for example.

```bash
$ git psuh
git: 'psuh' is not a git command. See 'git --help'.

Did you mean this?
  push
```

My proposal:
- [x] All documentation is properly cased (i.e. `JavaScript` not `javascript`)
- [x] `.unibeautifyrc` file language keys should be properly cased
  - [ ] When provided a configuration file with incorrectly spelt languages, Unibeautify should not automatically work, however, it should try to recommend to the user what changes should be made (i.e. `javascript` ==> `JavaScript`)
- [ ] Unibeautify CLI should recommend to the user when `-l <language>` is not found, find the best match

**Comment by stevenzeck** [comment]
_From @muuvmuuv on October 30, 2018 8:1_

@Glavin001 love that idea! 🎉

**Comment by stevenzeck** [comment]
_From @Glavin001 on October 30, 2018 22:0_

🎉 Awesome! I'm open to receiving a Pull Request to Unibeautify CLI which reports an error to the user for incorrectly spelt language names and then recommends similarly spelt languages for the user to fix.

I'm open to suggests on the message format. We can discuss in the PR.
For example:

```bash
$ unibeautify -f index.js -l javascript
Language 'javascript' is not found. Did you mean "JavaScript"?
```

**Comment by stevenzeck** [comment]
Right now we're waiting for [`unibeautify.beautify()`](https://github.com/Unibeautify/unibeautify-cli/blob/master/src/commands/BeautifyCommand.ts#L28-L29) to return the error `Cannot find language.`.

We can either handle it within the [catch](https://github.com/Unibeautify/unibeautify-cli/blob/master/src/commands/BeautifyCommand.ts#L36) or we can search for the language before we try to beautify.  We'll need to add a method to unibeautify to find the exact language so it's available in the API.

Or should we modify `LanguageManager.getLanguage()` to include a suggestion in the return?

**Comment by stevenzeck** [comment]
@Glavin001 @muuvmuuv @lassik any opinions on the above?

**Comment by lassik** [comment]
I wouldn't use an exception handler for this - seems a bit of a hack because we'd have to bounce back from the exception handler into the core for a second time.

IMHO it would be best for the CLI to pass a function (closure/callable) to the Unibeautify core. The function would be called in case the language doesn't match, and would suggest a more appropriate language using whatever criteria it wants. The function could take 2 arguments:

* the user-supplied language that didn't match
* a list of all available languages in Unibeautify core

What do you think?

**Comment by lassik** [comment]
Letting the CLI search for the language before beautifying would also be fine in in my opinion. Maybe the simplest.

**Comment by Glavin001** [comment]
@stevenzeck let’s try searching for language before, as suggested above.
