### ISSUE TITLE
Replace option not working

### ISSUE THREAD

**Issue by cdfa** [Unibeautify/unibeautify-cli#118]
With the latest npm version (0.4.0) the replace option with `-r` wasn't working. I noticed #55, where it was added and this was merged after the 0.4.0 released and updating to the latest master fxed the problem for me (using `-i`). Maybe it's time for a new release or why does the help text say the functionality was already in 0.4.0?

**Comment by stevenzeck** [comment]
Let me update the dependencies via #119 to fix security vulnerabilities, then I'll publish a new release.

**Comment by stevenzeck** [comment]
Published to 0.5.0.
