### ISSUE TITLE
Option to list all available languages

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify-cli#20]
This would also be good to have for users... Something like `--list-languages` or  `--help-languages`. Some other Unix tools have options like this ("list available file formats", etc.) but I don't recall them having particularly sensible option names, so I don't think it's worth looking them up.

We could just show them in the main `--help` screen but then it would be a mile long 😄 

How should we differentiate installed vs. uninstalled languages? It would be good to have some kind of status report on that, but I don't know whether it would be better to have that in the same option or a separate one.

**Comment by Glavin001** [comment]
Looks like @szeck87 has already started with https://github.com/Unibeautify/unibeautify-cli/pull/25

**Comment by Glavin001** [comment]
Closed by https://github.com/Unibeautify/unibeautify-cli/pull/28 and https://github.com/Unibeautify/unibeautify-cli/pull/25
Thanks @szeck87 

```
❯ node dist/cli.js list -l
Supported languages
1. CSS
2. GraphQL
3. JSON
4. JSX
5. JavaScript
6. Less
7. Markdown
8. PHP
9. SCSS
10. TypeScript
11. Vue

~/Development/unibeautify/unibeautify-cli commander-to-yargs*
❯ node dist/cli.js list -b
Supported beautifiers
1. @unibeautify/beautifier-php-cs-fixer
2. @unibeautify/beautifier-prettier
```
