### ISSUE TITLE
Configuration lookup options and precedence order

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify-cli#42]
Continued from #18:

> @szeck87: Loading a .unibeautifyrc.yml file does not work yet. When it will be supported, it will likely need to be passed in via the -c flag, but we'll see.

> @lassik: That's OK. I would suggest looking up .unibeautifyrc* based on the pathname of each beautified file by default (or from --file-path when given) since clang-format, git and countless other programs use a similar method. --config-file would override all of these, if given.

**Comment by lassik** [comment]
In my mind, the main problem with requiring users to pass `--config-file` manually is that then the logic to find `.unibeautifyrc*` needs to be coded separately in every program that uses the `unibeautify` CLI. The logic is non-trivial, so to have consistency and save duplicate code, it would be good if only `unibeautify` does the lookup. (If needed, `unibeautify` can have a separate command line option to only find the config file and print its pathname without beautifying anything.)

Another thing is that calling `unibeautify` from the command line should be simple for humans - the more required options we have, the more complex it is.

Anyway, using a `.unibeautifyrc` checked into version control should be the ordinary use case, right? In that case we can automatically try to find it using the same logic that e.g. Git uses to find the `.git` dir in this directory or its parent directories.

**Comment by szeck87** [comment]
What would be the purpose in differentiating whether it's beautifying from stdin versus a file (--stdin-filepath versus just --file-path)?  What's the difference between 3 and 4?  What do you mean by "each item inherits from the item below"?

Otherwise I think that precedence is mostly fine.  We're using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) search function for VSCode and Atom to find these files. `search` starts in the current directory, and continues going up one until it finds a config file. I think it would be best to do the same here.  So something like:

1. `--config-json`
2. `--config-file`
3. If neither are present, use cosmiconfig to search from the directory of the file being passed in `--file-path` on up until it finds something
4. Default settings (aka no settings coming from unibeautify)

**Comment by lassik** [comment]
Thanks for commenting.

> What would be the purpose in differentiating whether it's beautifying from stdin versus a file (--stdin-filepath versus just --file-path)?

Hmm. You may be right that there is indeed no point. I thought there were two use cases:

    $ unibeautify --language C test.c   # directly from file
    $ unibeautify --language C <test.c  # from stdin

In the second case (from stdin), `--file-path` could be used to artificially give a filename to help lookup the config file and to produce more intuituive error messages (#18). This is useful when stdin contents come from a disk file, but the file is modified in an editor so if we gave the filename to `unibeautify` directly, the contents of the file would be stale.

In the first case (directly from file), the filename is already given to `unibeautify`. There could be some use case where you'd want to override this filename, but I couldn't think of one. I guess there is no harm in permitting it anyway, so we could just as well go with the current `--file-path`.

> What's the difference between 3 and 4?

The difference is whether the filepath is a "fake" filepath coming from an option (`--file-path test.c`) or the "real" filepath coming from a non-option command line argument (just `test.c`). In case of the "fake" filepath, `unibeautify` wouldn't actually try to read the file contents from that path. It would only use that path to lookup the config file and as the filepath to show in error/warning messages (if any).

> What do you mean by "each item inherits from the item below"?

I mean that if e.g. the `--config-json` config is missing some options, and `--config-file` is also given, then the missing options would be read from the config file.

> Otherwise I think that precedence is mostly fine. We're using cosmiconfig search function for VSCode and Atom to find these files. search starts in the current directory, and continues going up one until it finds a config file. I think it would be best to do the same here.

Sounds good 😄  This is exactly what `clang-format` does to find the `.clang-format` file, and what Git does to find the `.gitignore` file, etc. So it's a very well-established convention.

cosmicconfig is not readily available from Emacs and many other non-JS environments so I think it would make sense for `unibeautify` CLI to do tasks where cosmicconfig is required/helpful.
