### ISSUE TITLE
Refactor to separate beautify and support paths

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify-cli#49]
Right now the logic/functionality for both beautifying and support are in the same file:  Runner.ts.  This file is getting long (196 lines as I'm writing this), and more is on the way.  I'm not sure what the best design is, maybe a superclass that has the common methods (`writeOut`, `writeError`, `exit`) and subclasses for each of the two pieces of functionality?  Or a main file that has those common methods and imports functions from the other two?  @Glavin001 thoughts?

**Comment by Glavin001** [comment]
I'll take a look tomorrow and we can discuss ideas on Slack 👍 .
