### ISSUE TITLE
(Clean) npm install results in SyntaxError in cli.js 

### ISSUE THREAD

**Issue by eyecatchup** [Unibeautify/unibeautify-cli#5]
### Steps to reproduce

Pre-Requirement: Uninstall any unibeautify installations (or test with local install).

```sh
# step 1 
$ npm install -g unibeautify-cli
# step 2
$ npm install -g beautifier-prettydiff
# step 3
echo "function(n){return n+1;}" | unibeautify --language JavaScript --config-json '{"JavaScript":{"insize":2,"inchar":" "}}'
```
### Expected result

```js
function (n) {
    return n + 1;
} 
```

### Actual result

```
C:\Users\ssc\AppData\Roaming\npm\node_modules\unibeautify-cli\src\cli.js:15
const { args: files, language, outFile, replace, configFile, configJson } = programArgs;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

### System info

- Node version: 5.5.0
- Platform: Windows

### Additional info

- Full terminal log: https://gist.github.com/eyecatchup/5ff8fc22886561c34a1fdd315fdcfa3a.pibb?file=install.log
- The installed cli.js: https://gist.github.com/eyecatchup/5ff8fc22886561c34a1fdd315fdcfa3a.pibb?file=cli.js

**Comment by eyecatchup** [comment]
Thanks to [the warning of the required `sb-exec` package](https://gist.github.com/eyecatchup/5ff8fc22886561c34a1fdd315fdcfa3a#file-install-log-L29), I thought I should just try to update node in order to fix *this* issue too.

Updating node from `5.5.0` to `6.10.0` (current LTS version) solved the issue in fact (which is an issue for the main package too, by the way). 

I send a PR to fix this issue and avoid potential further confusion with other users of unsupported engine versions.

If you don't want to raise the engine requirement from 4.* to 6.*, you'd probably only need to change the argument assignment again.

**Comment by Glavin001** [comment]
Closed by PR: https://github.com/Unibeautify/unibeautify/pull/6
